[versions]
spock = "2.0-groovy-3.0"

[libraries]
jackson-platform = { group = "com.fasterxml.jackson", name = "jackson-bom", version = "2.14.2" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind" }
jackson-parameter-names = { group = "com.fasterxml.jackson.module", name = "jackson-module-parameter-names" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }

apache-httpclient = { group = "org.apache.httpcomponents.client5", name = "httpclient5", version = "5.1.2" }
apache-commons-io = { group = "commons-io", name = "commons-io", version = "2.11.0" }

spock_core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
spock_junit4 = { group = "org.spockframework", name = "spock-junit4", version.ref = "spock" }
