name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: 17
            distribution: temurin

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        run: ./gradlew build

  test-gradle-version:
    needs: quick-check
    strategy:
      fail-fast: false
      matrix:
        # Test newest 5.x, 6.x and 7.x, plus oldest patched 7.x and 8.x
        # Latest 8.x is tested in 'quick-check' job
        gradle-version: [ "5.6.4", "6.9.4", "7.0.2", "7.6.1", "8.0.2"]
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Execute Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -S build -DtestGradleVersion=${{ matrix.gradle-version }}

  self-test:
      needs: quick-check
      runs-on: ubuntu-latest
      env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      steps:
          - uses: actions/checkout@v3

          - name: Set up JDK
            uses: actions/setup-java@v3
            with:
                java-version: 11
                distribution: temurin

          - name: Set up Gradle
            uses: gradle/gradle-build-action@v2

          - name: Self Test :plugin
            run: ./plugin-self-test
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Save plugin JSON report
            uses: actions/upload-artifact@v3
            with:
                name: plugin-json
                path: build/reports/github-dependency-graph-plugin/github-dependency-snapshot.json
                if-no-files-found: error

